const itemsAnimales = [
    {
        id: 1,
        categoria: "Animales",
        nombre: "leon",
        precio: 350.00,
        img: "img/leon.jpg",
        descripcion: "León tejido en crochet.",
    },
    {
        id: 2,
        categoria: "Animales",
        nombre: "Elefantes",
        precio: 450.00,
        img:"img/elefantes.jpg",
        descripcion: "Elefante tejido en crochet, colores azúl y rosa.",
    },
    {
        id: 3,
        categoria: "Animales",
        nombre: "Perrito",
        precio: 420.00,
        img: "img/frida.jpg",
        descripcion: "Perrito de rescate 'Frida' tejido en crochet.",
    },
    {
        id: 4,
        categoria: "Animales",
        nombre: "Koala",
        precio: 390.00,
        img: "img/koala.jpg",
        descripcion: "Koala tejido en crochet",
    },
    {
        id: 5,
        categoria: "Animales",
        nombre: "Taz",
        precio: 390.00,
        img: "img/Taz.jpg",
        descripcion: "Demonio de Tazmania tejido en crochet",
    },
    {
        id: 6,
        categoria: "Animales",
        nombre: "Unicornio",
        precio: 390.00,
        img: "img/unicornio.jpg",
        descripcion: "Unicornio bebé tejido en crochet",
    },
];

